"""empty message

Revision ID: 9473217df35a
Revises: 
Create Date: 2023-05-15 09:28:50.164535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9473217df35a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('horario', sa.Date(), nullable=True))
    op.alter_column('usuario', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.alter_column('usuario', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('usuario', 'horario')
    # ### end Alembic commands ###
